language: c
dist: xenial
sudo: required

arch:
    - amd64
    - arm64

addons:
    apt:
        packages:
            - asciidoctor
            - automake
            - autoconf
            - doxygen
            - graphviz
            - libconfig-dev
            - libssl-dev
            - libtool
            - mscgen
            - pkg-config

compiler:
    - gcc
    - clang

script:
    - ./scripts/build.sh

jobs:
    include:
        - stage: test
          env: TEST=documentation
          script:
              - ./scripts/build.sh
              - make doxygen-doc
          before_deploy:
              - pushd doc
              - mkdir gh-pages
              - cp -r event_machine_api/html/* gh-pages/
              - popd
          deploy:
              provider: pages
              skip_cleanup: true
              local_dir: doc/gh-pages
              github_token: $GH_REPO_TOKEN
              on:
                  branch: master
                  condition: "x$GH_REPO_TOKEN != x"
