language: c
dist: xenial
sudo: required

arch:
    - amd64
    - arm64

addons:
    apt:
        packages:
            - automake
            - autoconf
            - libconfig-dev
            - libssl-dev
            - libtool
            - pkg-config

compiler:
    - gcc
    - clang

script:
    - ./scripts/build.sh
